import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Compass,Plus,Radio,MessageCircle,Store,ShoppingBag,Gamepad2,Wallet,ShieldCheck,Brain,Users,BarChart3,Gift,UserCircle,Settings,Search,Bell,Video,Heart,MessageSquare,Share2,Bookmark,Send,Globe2,Lock,ChevronLeft,Menu, Sparkles, Megaphone, Package, CreditCard, Link2, Trophy, Mic2, Phone, Camera, Eye, Zap} from 'lucide-react';
import './styles.css';

const features=[
 ['الحساب والأمان','حسابات بالهاتف والإيميل، 2FA، استعادة، الخصوصية، إدارة الجلسات والتحقق عند الحاجة.',UserCircle],
 ['الشبكة الاجتماعية','أصدقاء، متابعة، منشورات، Stories، تعليقات، تفاعلات، مشاركة، حفظ وكتم.',Users],
 ['المحادثات','رسائل خاصة غير محدودة، وسائط وملفات، رسائل مختفية، صوت وفيديو ومكالمات جماعية.',MessageCircle],
 ['الذكاء الاصطناعي','محادثة AI، كتابة وتحسين وترجمة، دعم، كشف Spam/Fraud ومساعد التاجر.',Brain],
 ['LIVE والمبدعون','بث فردي وDuo وGrid وPK، هدايا، تحديات، إحصائيات وأرباح.',Radio],
 ['الهدايا والمحفظة','شراء وإرسال الهدايا، العمولات، السحب، السجلات وكشف الاحتيال.',Gift],
 ['الترفيه','Watch Party، ألعاب، غرف صوتية، Radio، مسابقات وتحديات.',Gamepad2],
 ['المتاجر','متجر، منتجات، مخزون، طلبات، عملاء، خصومات، Landing وتحليلات.',Store],
 ['الترويج والإعلانات','استهداف محلي ووطني ودولي، مدة وميزانية وتقدير وصول قبل الدفع.',Megaphone],
 ['الإحالة','/ref/username، 10% من الاشتراكات المؤهلة ولوحة أرباح وإحصائيات.',Link2],
 ['الأمان والمراقبة','حماية متعددة الطبقات، مكافحة إساءة الاستخدام، سجلات وتنبيهات ومراجعة بشرية.',ShieldCheck],
 ['لوحة الإدارة','/admin/bots، صحة الخدمات، التهديدات، الأخطاء، الدعم، المالية وPANIC.',BarChart3]
];
const posts=[
 {name:'سارة أحمد',text:'أهلاً بكم في تواصل 🌍 منصة تجمع المجتمع والمحتوى والتجارة في مكان واحد.',likes:248,type:'اجتماعي'},
 {name:'متجر النخبة',text:'وصلت منتجات جديدة! اكتشف المتجر والعروض اليوم.',likes:91,type:'منتج'},
 {name:'محمد صانع محتوى',text:'LIVE الليلة الساعة 20:00 — تحدي وألعاب وهدايا 🎁',likes:532,type:'LIVE'}
];
const stores=[['متجر النخبة','120 منتج','2.4K زيارة'],['Dz Fashion','58 منتج','1.8K زيارة'],['Tech DZ','34 منتج','960 زيارة']];
function App(){
 const [tab,setTab]=useState('home'); const [liked,setLiked]=useState({}); const [menu,setMenu]=useState(false); const [ai,setAi]=useState('');
 const nav=[['home','الرئيسية',Home],['discover','اكتشاف',Compass],['create','إنشاء',Plus],['live','LIVE',Radio],['messages','الرسائل',MessageCircle]];
 const title=useMemo(()=>({home:'الرئيسية',discover:'اكتشاف',create:'إنشاء',live:'LIVE',messages:'الرسائل',store:'المتاجر',market:'السوق',games:'الألعاب',ai:'مساعد AI',security:'الأمان والخصوصية',wallet:'المحفظة',analytics:'التحليلات',admin:'إدارة المنصة'}[tab]||'تواصل'),[tab]);
 const FeatureGrid=()=> <div className="featuregrid">{features.map(([t,d,I])=><div className="feature" key={t}><I/><div><b>{t}</b><p>{d}</p></div></div>)}</div>;
 const render=()=>{
  if(tab==='discover') return <section><PageHead title="اكتشاف" sub="محتوى، بثوث، متاجر وألعاب حولك."/><div className="chips"><span>🔥 الرائج</span><span>🎬 فيديو</span><span>🔴 LIVE</span><span>🛍️ منتجات</span><span>👥 مجتمعات</span></div><div className="grid">{['صناع محتوى','متاجر','LIVE الآن','مجتمعات','تحديات','منتجات رائجة'].map(x=><div className="card" key={x}><Sparkles/><b>{x}</b><p>اكتشف محتوى جديد يناسب اهتماماتك.</p><button className="outline">استكشف</button></div>)}</div></section>;
  if(tab==='create') return <section><PageHead title="إنشاء" sub="حوّل فكرتك إلى محتوى أو منتج أو حملة."/><div className="creategrid">{['منشور','Story','فيديو قصير','LIVE','منتج','صفحة هبوط','حملة ترويج','غرفة صوتية'].map(x=><button className="big" key={x} onClick={()=>setTab(x==='LIVE'?'live':'home')}><Plus/> {x}</button>)}</div></section>;
  if(tab==='live') return <section><PageHead title="LIVE" sub="بث فردي، Duo، Grid، PK وتحديات."/><div className="livegrid">{['LIVE الآن','Duo','Grid','PK','Top Live','تحديات'].map((x,i)=><div className="livecard" key={x}><div className="livecover"><Radio/><span>{i+12}K</span></div><b>{x}</b><small>مبدعون من الجزائر والعالم</small><button>دخول</button></div>)}</div></section>;
  if(tab==='messages') return <section><PageHead title="الرسائل" sub="محادثات خاصة، مكالمات صوت وفيديو."/><div className="chatlayout"><div className="chatlist">{['سارة أحمد','محمد صانع محتوى','متجر النخبة','فريق تواصل'].map((x,i)=><button key={x} className="chatrow"><div className="avatar sm">{x[0]}</div><div><b>{x}</b><small>{i?'آخر رسالة منذ دقائق':'متصل الآن'}</small></div><span>›</span></button>)}</div><div className="chatbox"><MessageCircle/><h3>ابدأ محادثة</h3><p>الرسائل والوسائط والمكالمات تصبح Realtime عند ربط مزود البنية الخلفية.</p><div className="chatactions"><button><Phone/> صوت</button><button><Video/> فيديو</button><button><Send/> إرسال</button></div></div></div></section>;
  if(tab==='store') return <section><PageHead title="المتاجر" sub="أنشئ متجرك وابدأ البيع."/><div className="dashboard"><div className="stat"><Store/><b>3</b><small>متاجر</small></div><div className="stat"><Package/><b>212</b><small>منتجات</small></div><div className="stat"><ShoppingBag/><b>48</b><small>طلبات</small></div><div className="stat"><BarChart3/><b>6.8K</b><small>زيارات</small></div></div><div className="card"><button className="primary"><Plus/> إنشاء متجر</button><h3>متاجرك</h3>{stores.map(s=><div className="storeRow" key={s[0]}><div className="avatar">م</div><div><b>{s[0]}</b><small>{s[1]} · {s[2]}</small></div><button className="outline">إدارة</button></div>)}</div></section>;
  if(tab==='market') return <section><PageHead title="السوق" sub="منتجات ومتاجر داخل تواصل."/><div className="grid">{['هاتف ذكي','سماعات','قميص جزائري','حقيبة','عطر','إكسسوار'].map((x,i)=><div className="product" key={x}><div className="productpic"><ShoppingBag/></div><b>{x}</b><small>متجر موثوق · الجزائر</small><strong>{(i+1)*1500} دج</strong><button className="primary">شراء</button></div>)}</div></section>;
  if(tab==='games') return <section><PageHead title="الترفيه" sub="ألعاب ومشاهدة ومنافسات اجتماعية."/><div className="grid">{['Watch Party','سينما جماعية','XO','Domino','Ludo','Chess','غرف صوتية','Radio','مسابقات'].map(x=><div className="card game"><Gamepad2/><b>{x}</b><p>غرفة جاهزة للانضمام واللعب.</p><button className="primary">دخول</button></div>)}</div></section>;
  if(tab==='ai') return <section><PageHead title="مساعد AI" sub="مساعد ذكي للمحتوى، الدعم، المتاجر والحملات."/><div className="aihero"><Brain/><h2>كيف أساعدك؟</h2><p>اكتب طلبك وسأجهز لك مسودة أو تحليلًا داخل المنصة.</p><div className="aibox"><input value={ai} onChange={e=>setAi(e.target.value)} placeholder="مثال: اكتب إعلانًا لمنتج ملابس..."/><button onClick={()=>setAi('سأجهز لك تحليل الجمهور + عنوان + إعلان + عرض + أفكار لتحسين Landing والميزانية.')}>إرسال</button></div></div><FeatureGrid/></section>;
  if(tab==='security') return <section><PageHead title="الأمان والخصوصية" sub="تحكم في بياناتك وجلساتك وإعدادات الحماية."/><div className="securitygrid">{[['2FA','مفعّل',Lock],['الجلسات','3 أجهزة',ShieldCheck],['الخصوصية','الأصدقاء',Eye],['التحقق','عند الحاجة',UserCircle],['Spam/Fraud','مراقبة',Zap],['المحتوى','مراجعة تدريجية',ShieldCheck]].map(([a,b,I])=><div className="card"><I/><b>{a}</b><small>{b}</small><button className="outline">إدارة</button></div>)}</div></section>;
  if(tab==='wallet') return <section><PageHead title="المحفظة" sub="اشتراكات، هدايا، إحالات وأرباح."/><div className="wallet"><Wallet/><b>0 دج</b><small>الرصيد المتاح</small><div><button className="primary">شحن</button><button className="outline">سحب</button></div></div><div className="dashboard"><div className="stat"><Gift/><b>0</b><small>هدايا</small></div><div className="stat"><Link2/><b>0</b><small>إحالات</small></div><div className="stat"><Megaphone/><b>0</b><small>حملات</small></div></div></section>;
  if(tab==='analytics') return <section><PageHead title="التحليلات" sub="أداء المحتوى والمتجر والحملات."/><div className="dashboard">{[['زيارات','6,820'],['مشاهدات','21,430'],['طلبات','48'],['مبيعات','312K دج'],['تحويل','3.7%'],['أرباح','84K دج']].map(([a,b])=><div className="stat"><BarChart3/><b>{b}</b><small>{a}</small></div>)}</div><div className="card chart"><BarChart3/><h3>أداء آخر 30 يومًا</h3><div className="bars">{[25,45,32,65,50,80,72,90,60,78,55,95].map((h,i)=><i style={{height:h+'%'}} key={i}/>)}</div></div></section>;
  if(tab==='admin') return <section><PageHead title="إدارة المنصة" sub="مراقبة الخدمات والتهديدات والمالية."/><div className="adminGrid">{[['Workers','24,680 نشط'],['هجمات مصدودة','18,421'],['أخطاء','12'],['دعم','143'],['سحوبات','27'],['أرباح','4.8M دج'],['Logs','1.2M'],['حالة الخدمات','99.98%']].map(([a,b])=><div className="card"><BarChart3/><b>{a}</b><strong>{b}</strong></div>)}</div><button className="panic">PANIC — إيقاف فريق الحماية</button></section>;
  return <section><div className="welcome"><div><small>منصة اجتماعية وتجارية جزائرية للعالم</small><h1>تواصل</h1><p>تواصل، اكتشف، أنشئ، ابث، العب، وبِع — في منصة واحدة.</p><div className="heroBtns"><button className="white" onClick={()=>setTab('create')}>ابدأ الآن</button><button className="ghost" onClick={()=>setTab('discover')}>اكتشف</button></div></div><div className="heroLogo">ت</div></div><div className="stories">{['قصتك','سارة','محمد','متجر','LIVE'].map(x=><div className="story" key={x}><div className="storypic">{x[0]}</div><small>{x}</small></div>)}</div>{posts.map((p,i)=><article className="post" key={i}><header><div className="avatar sm">{p.name[0]}</div><div><b>{p.name}</b><small>{p.type} · الآن</small></div><button className="icon">•••</button></header><p>{p.text}</p><div className="media">{p.type==='LIVE'?<Video/>:p.type==='منتج'?<ShoppingBag/>:<Heart/>}<span>{p.type==='LIVE'?'بث مباشر':p.type==='منتج'?'منتج قابل للشراء':'محتوى اجتماعي'}</span></div><footer><button onClick={()=>setLiked({...liked,[i]:!liked[i]})}><Heart fill={liked[i]?'currentColor':'none'}/> {p.likes+(liked[i]?1:0)}</button><button><MessageSquare/> تعليق</button><button><Share2/> مشاركة</button><button><Bookmark/> حفظ</button></footer></article>)}<div className="card"><h2>كل المنصة في مكان واحد</h2><p>هذه النسخة تطبق البنية والواجهات الأساسية لكل المجالات المذكورة، مع طبقات جاهزة لربط الخدمات الحقيقية.</p><FeatureGrid/></div></section>;
 };
 const PageHead=({title,sub})=><div className="pagehead"><div><h1>{title}</h1><p>{sub}</p></div><button className="icon" onClick={()=>setMenu(!menu)}><Menu/></button></div>;
 return <><header className="top"><button className="brand" onClick={()=>setTab('home')}>تواصل</button><div className="search"><Search/><span>بحث عن أشخاص، فيديوهات، متاجر...</span></div><div className="actions"><button><Bell/></button><button onClick={()=>setTab('wallet')}><Wallet/></button></div></header><main><aside><div className="profilemini"><div className="avatar">ت</div><b>حسابك</b><small>@tawasol</small></div>{[['store','المتجر',Store],['market','السوق',ShoppingBag],['games','الألعاب',Gamepad2],['ai','مساعد AI',Brain],['analytics','التحليلات',BarChart3],['wallet','المحفظة',Wallet],['security','الأمان والخصوصية',ShieldCheck],['admin','الإدارة',Settings]].map(([id,l,I])=><button className={tab===id?'sel':''} onClick={()=>setTab(id)} key={id}><I/> {l}</button>)}</aside><div className="content">{render()}</div></main><nav className="bottom">{nav.map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/><span>{label}</span></button>)}</nav></>}
createRoot(document.getElementById('root')).render(<App/>);
